CREATE OR REPLACE VIEW STATS_USER.VGUEST_STATS_VW
(GUEST_NAME,CPUs,MEMORY_MB,PROVISIONED_GB,USED_GB,FREE_SPACE_GB,CLUSTER_NAME,DATACENTER)
AS
SELECT 
  VG.VGUEST_NAME
  , VGS.CPUS
  , VGS.MEMORY_MB
  , ROUND(VGS.PROVISIONED_MB/1024,1) PROVISIONED_GB
  , ROUND(VGS.IN_USE_MB/1024,1) USED_GB
  , ROUND((VGS.PROVISIONED_MB - VGS.IN_USE_MB)/1024,1) FREE_SPACE_GB
  , VC.VCLUSTER_NAME
  , DI.DATACENTER_NAME
FROM VMWARE_VGUEST_STATS VGS
INNER JOIN VMWARE_VGUEST VG ON VGS.VGUEST_ID = VG.VGUEST_ID
INNER JOIN VMWARE_VHOST VH ON VH.VHOST_ID = VGS.VM_VHOST_ID
INNER JOIN VMWARE_VCLUSTER VC ON VC.VCLUSTER_ID = VH.VCLUSTER_ID
INNER JOIN DATACENTER_INFO DI ON DI.DATACENTER_ID = VC.DATACENTER_ID
WHERE VGS.run_log_id = (SELECT MAX(run_log_id) from STATS_USER.VMWARE_VGUEST_STATS)
ORDER BY VC.VCLUSTER_ID, VH.VHOST_ID;