create or replace PROCEDURE                       INSERT_VINFO_STG 
(
v_vm_name VARCHAR2,
v_powerstate VARCHAR2,
v_is_template VARCHAR2,
v_config_status VARCHAR2,
v_dns_name VARCHAR2,
v_connection_state VARCHAR2,
v_guest_state VARCHAR2,
v_heartbeat VARCHAR2,
v_consolidation_needed VARCHAR2,
v_poweron VARCHAR2,
v_suspend_time VARCHAR2,
v_change_version VARCHAR2,
v_cpus NUMBER,
v_memory_mb NUMBER,
v_nics NUMBER,
v_num_disks NUMBER,
v_network_1 VARCHAR2,
v_network_2 VARCHAR2,
v_network_3 VARCHAR2,
v_network_4 VARCHAR2,
v_num_monitors NUMBER,
v_video_ram_kb NUMBER,
v_resource_pool VARCHAR2,
v_vm_folder VARCHAR2,
v_vapp VARCHAR2,
v_das_protection VARCHAR2,
v_ft_state VARCHAR2,
v_ft_latency VARCHAR2,
v_ft_bandwidth NUMBER,
v_ft_sec_latencey NUMBER,
v_provisioned_mb NUMBER,
v_in_use_mb NUMBER,
v_unshared_mb NUMBER,
v_ha_restart_policy VARCHAR2,
v_ha_isolation_response VARCHAR2,
v_ha_vm_monitoring VARCHAR2,
v_cluster_rules VARCHAR2,
v_cluster_rule_names VARCHAR2,
v_boot_required VARCHAR2,
v_boot_delay NUMBER,
v_boot_retry_delay NUMBER,
v_boot_retry_enabled VARCHAR2,
v_boot_bios_setup VARCHAR2,
v_firmware VARCHAR2,
v_hw_version NUMBER,
v_hw_upgrade VARCHAR2,
v_hw_upgrade_policy VARCHAR2,
v_hw_target VARCHAR2,
v_vm_path VARCHAR2,
v_annotation VARCHAR2,
v_com_emc_avamar_vmware_snap VARCHAR2,
v_com_vmware_vdp2_isprotected VARCHAR2,
v_com_vmware_vdp2_protectedby VARCHAR2,
v_datacenter VARCHAR2,
v_vm_cluster VARCHAR2,
v_vm_host VARCHAR2,
v_os_config_file VARCHAR2,
v_os_vmware_tools VARCHAR2,
v_vm_id VARCHAR2,
v_vm_uuid VARCHAR2,
v_vcenter_uuid VARCHAR2
)

AS
BEGIN
  INSERT INTO RVTOOLS_VINFO_STG VALUES (v_vm_name,
v_powerstate,
v_is_template,
v_config_status,
v_dns_name,
v_connection_state,
v_guest_state,
v_heartbeat,
v_consolidation_needed,
v_poweron,
v_suspend_time,
v_change_version,
v_cpus,
v_memory_mb,
v_nics,
v_num_disks,
v_network_1,
v_network_2,
v_network_3,
v_network_4,
v_num_monitors,
v_video_ram_kb,
v_resource_pool,
v_vm_folder,
v_vapp,
v_das_protection,
v_ft_state,
v_ft_latency,
v_ft_bandwidth,
v_ft_sec_latencey,
v_provisioned_mb,
v_in_use_mb,
v_unshared_mb,
v_ha_restart_policy,
v_ha_isolation_response,
v_ha_vm_monitoring,
v_cluster_rules,
v_cluster_rule_names,
v_boot_required,
v_boot_delay,
v_boot_retry_delay,
v_boot_retry_enabled,
v_boot_bios_setup,
v_firmware,
v_hw_version,
v_hw_upgrade,
v_hw_upgrade_policy,
v_hw_target,
v_vm_path,
v_annotation,
v_com_emc_avamar_vmware_snap,
v_com_vmware_vdp2_isprotected,
v_com_vmware_vdp2_protectedby,
v_datacenter,
v_vm_cluster,
v_vm_host,
v_os_config_file,
v_os_vmware_tools,
v_vm_id,
v_vm_uuid,
v_vcenter_uuid
);
  commit; 
END;