create or replace PROCEDURE                       INSERT_VHOST_STG 
(
v_host_name VARCHAR2,
v_datacenter VARCHAR2,
v_vm_cluster VARCHAR2,
v_config_status VARCHAR2,
v_cpu_model VARCHAR2,
v_speed NUMBER,
v_ht_available VARCHAR2,
v_ht_active VARCHAR2,
v_cpu_count NUMBER,
v_cores_per_cpu NUMBER,
v_num_cores NUMBER,
v_percent_cpu_usage NUMBER,
v_memory_size NUMBER,
v_percent_memory_used NUMBER,
v_console NUMBER,
v_count_nic NUMBER,
v_count_hba NUMBER,
v_count_vm NUMBER,
v_vms_per_core NUMBER,
v_count_vcpu NUMBER,
v_vcpu_per_core NUMBER,
v_vram NUMBER,
v_vm_used_memory NUMBER,
v_vm_memory_swapped NUMBER,
v_vm_memory_balooned NUMBER,
v_vmotion_support VARCHAR2,
v_storage_vmotion_support VARCHAR2,
v_current_evc VARCHAR2,
v_max_evc VARCHAR2,
v_esx_version VARCHAR2,
v_boot_time VARCHAR2,
v_dns_servers VARCHAR2,
v_dhcp VARCHAR2,
v_domain VARCHAR2,
v_dns_search VARCHAR2,
v_ntp_servers VARCHAR2,
v_ntpd_running VARCHAR2,
v_host_time_zone VARCHAR2,
v_time_zone_name VARCHAR2,
v_gmt_offset NUMBER,
v_vendor VARCHAR2,
v_host_model VARCHAR2,
v_service_tag VARCHAR2,
v_oem_specific_string VARCHAR2,
v_bios_version VARCHAR2,
v_bios_date VARCHAR2,
v_object_id VARCHAR2,
v_vcenter_uuid VARCHAR2
)

AS
BEGIN
  INSERT INTO RVTOOLS_VHOST_STG VALUES (v_host_name,
v_datacenter,
v_vm_cluster,
v_config_status,
v_cpu_model,
v_speed,
v_ht_available,
v_ht_active,
v_cpu_count,
v_cores_per_cpu,
v_num_cores,
v_percent_cpu_usage,
v_memory_size,
v_percent_memory_used,
v_console,
v_count_nic,
v_count_hba,
v_count_vm,
v_vms_per_core,
v_count_vcpu,
v_vcpu_per_core,
v_vram,
v_vm_used_memory,
v_vm_memory_swapped,
v_vm_memory_balooned,
v_vmotion_support,
v_storage_vmotion_support,
v_current_evc,
v_max_evc,
v_esx_version,
v_boot_time,
v_dns_servers,
v_dhcp,
v_domain,
v_dns_search,
v_ntp_servers,
v_ntpd_running,
v_host_time_zone,
v_time_zone_name,
v_gmt_offset,
v_vendor,
v_host_model,
v_service_tag,
v_oem_specific_string,
v_bios_version,
v_bios_date,
v_object_id,
v_vcenter_uuid
);
  commit; 
END;