create or replace PROCEDURE                                  INSERT_VCLUSTER_STG 
(
v_name VARCHAR2,
v_config_status VARCHAR2,
v_overall_status VARCHAR2,
v_num_hosts NUMBER,
v_num_effective_hosts NUMBER,
v_total_cpu NUMBER,
v_num_cpu_cores NUMBER,
v_num_cpu_threads NUMBER,
v_effective_cpu NUMBER,
v_total_memory NUMBER,
v_effective_memory NUMBER,
v_num_vmotions NUMBER,
v_ha_enabled VARCHAR2,
v_failover_level NUMBER,
v_admission_control_enabled VARCHAR2,
v_host_monitoring VARCHAR2,
v_hb_ds_candidate_policy VARCHAR2,
v_isolation_response VARCHAR2,
v_restart_priority VARCHAR2,
v_cluster_settings VARCHAR2,
v_max_failures NUMBER,
v_max_failure_window NUMBER,
v_failure_interval NUMBER,
v_min_uptime NUMBER,
v_vm_monitoring VARCHAR2,
v_drs_enabled VARCHAR2,
v_drs_default_vm_behavior VARCHAR2,
v_drs_vmotion_rate NUMBER,
v_dpm_enabled VARCHAR2,
v_dpm_default_behavior VARCHAR2,
v_dpm_host_power_action_rate NUMBER,
v_vcenter_uuid VARCHAR2
)

AS
BEGIN
  INSERT INTO RVTOOLS_VCLUSTER_STG VALUES (v_name,
v_config_status,
v_overall_status,
v_num_hosts,
v_num_effective_hosts,
v_total_cpu,
v_num_cpu_cores,
v_num_cpu_threads,
v_effective_cpu,
v_total_memory,
v_effective_memory,
v_num_vmotions,
v_ha_enabled,
v_failover_level,
v_admission_control_enabled,
v_host_monitoring,
v_hb_ds_candidate_policy,
v_isolation_response,
v_restart_priority,
v_cluster_settings,
v_max_failures,
v_max_failure_window,
v_failure_interval,
v_min_uptime,
v_vm_monitoring,
v_drs_enabled,
v_drs_default_vm_behavior,
v_drs_vmotion_rate,
v_dpm_enabled,
v_dpm_default_behavior,
v_dpm_host_power_action_rate,
v_vcenter_uuid
);
  commit; 
END;